version: "3.8"
services:
  database:
    hostname: database
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: guess-the-artist
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo_volume:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  database:
